-- 코드를 작성해주세요

SELECT B.A AS YEAR, (B.M-T1.SIZE_OF_COLONY) AS YEAR_DEV, T1.ID FROM ECOLI_DATA AS T1 JOIN (SELECT MAX(SIZE_OF_COLONY) AS M, YEAR(DIFFERENTIATION_DATE) AS A FROM ECOLI_DATA GROUP BY A) AS B ON YEAR(DIFFERENTIATION_DATE) = B.A ORDER BY YEAR, YEAR_DEV