-- 코드를 입력하세요

SELECT CATEGORY, SUM(SALES) FROM BOOK JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01' GROUP BY CATEGORY ORDER BY CATEGORY